/**
 * SealProof — PM2 Production Configuration
 *
 * Differences from development:
 * - NODE_ENV=production
 * - Cluster mode for stateless services
 * - Log rotation enabled
 * - Max memory restart thresholds
 * - Graceful reload with wait_ready
 */
module.exports = {
  apps: [
    // =========================================================================
    // Backend Microservices (15 services)
    // =========================================================================
    {
      name: 'sp-notary-commission',
      script: 'services/notary-commission-svc/src/index.js',
      instances: 2,
      exec_mode: 'cluster',
      env: { NODE_ENV: 'production', PORT: 4001 },
      max_memory_restart: '512M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/notary-commission-error.log',
      out_file: '/var/log/sealproof/notary-commission-out.log',
      merge_logs: true,
    },
    {
      name: 'sp-notary-roster',
      script: 'services/notary-roster-svc/src/index.js',
      instances: 2,
      exec_mode: 'cluster',
      env: { NODE_ENV: 'production', PORT: 4002 },
      max_memory_restart: '512M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/notary-roster-error.log',
      out_file: '/var/log/sealproof/notary-roster-out.log',
      merge_logs: true,
    },
    {
      name: 'sp-session-orchestrator',
      script: 'services/session-orchestrator-svc/src/index.js',
      instances: 2,
      exec_mode: 'cluster',
      env: { NODE_ENV: 'production', PORT: 4003 },
      max_memory_restart: '1G',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/session-orchestrator-error.log',
      out_file: '/var/log/sealproof/session-orchestrator-out.log',
      merge_logs: true,
    },
    {
      name: 'sp-kyc',
      script: 'services/kyc-svc/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 4004 },
      max_memory_restart: '256M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/kyc-error.log',
      out_file: '/var/log/sealproof/kyc-out.log',
    },
    {
      name: 'sp-livekit-bridge',
      script: 'services/livekit-bridge-svc/src/index.js',
      instances: 2,
      exec_mode: 'cluster',
      env: { NODE_ENV: 'production', PORT: 4005 },
      max_memory_restart: '512M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/livekit-bridge-error.log',
      out_file: '/var/log/sealproof/livekit-bridge-out.log',
      merge_logs: true,
    },
    {
      name: 'sp-esign-bridge',
      script: 'services/esign-bridge-svc/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 4006 },
      max_memory_restart: '256M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/esign-bridge-error.log',
      out_file: '/var/log/sealproof/esign-bridge-out.log',
    },
    {
      name: 'sp-journal',
      script: 'services/journal-svc/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 4007 },
      max_memory_restart: '256M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/journal-error.log',
      out_file: '/var/log/sealproof/journal-out.log',
    },
    {
      name: 'sp-recording',
      script: 'services/recording-svc/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 4008 },
      max_memory_restart: '512M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/recording-error.log',
      out_file: '/var/log/sealproof/recording-out.log',
    },
    {
      name: 'sp-seal-applicator',
      script: 'services/seal-applicator-svc/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 4009 },
      max_memory_restart: '256M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/seal-applicator-error.log',
      out_file: '/var/log/sealproof/seal-applicator-out.log',
    },
    {
      name: 'sp-payment',
      script: 'services/payment-svc/src/index.js',
      instances: 2,
      exec_mode: 'cluster',
      env: { NODE_ENV: 'production', PORT: 4010 },
      max_memory_restart: '512M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/payment-error.log',
      out_file: '/var/log/sealproof/payment-out.log',
      merge_logs: true,
    },
    {
      name: 'sp-notification',
      script: 'services/notification-svc/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 4011 },
      max_memory_restart: '256M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/notification-error.log',
      out_file: '/var/log/sealproof/notification-out.log',
    },
    {
      name: 'sp-audit-export',
      script: 'services/audit-export-svc/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 4012 },
      max_memory_restart: '256M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/audit-export-error.log',
      out_file: '/var/log/sealproof/audit-export-out.log',
    },
    {
      name: 'sp-api-gateway',
      script: 'services/api-gateway-svc/src/index.js',
      instances: 2,
      exec_mode: 'cluster',
      env: { NODE_ENV: 'production', PORT: 4013 },
      max_memory_restart: '512M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/api-gateway-error.log',
      out_file: '/var/log/sealproof/api-gateway-out.log',
      merge_logs: true,
    },
    {
      name: 'sp-webhook',
      script: 'services/webhook-svc/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 4014 },
      max_memory_restart: '256M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/webhook-error.log',
      out_file: '/var/log/sealproof/webhook-out.log',
    },
    {
      name: 'sp-tenant',
      script: 'services/tenant-svc/src/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 4015 },
      max_memory_restart: '256M',
      wait_ready: true,
      listen_timeout: 10000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/tenant-error.log',
      out_file: '/var/log/sealproof/tenant-out.log',
    },

    // =========================================================================
    // Frontend Apps (3 Next.js apps)
    // =========================================================================
    {
      name: 'sp-customer-web',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: 'apps/customer-web',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 3000 },
      max_memory_restart: '1G',
      wait_ready: true,
      listen_timeout: 30000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/customer-web-error.log',
      out_file: '/var/log/sealproof/customer-web-out.log',
    },
    {
      name: 'sp-notary-web',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: 'apps/notary-web',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 3001 },
      max_memory_restart: '1G',
      wait_ready: true,
      listen_timeout: 30000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/notary-web-error.log',
      out_file: '/var/log/sealproof/notary-web-out.log',
    },
    {
      name: 'sp-admin-web',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: 'apps/admin-web',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 3002 },
      max_memory_restart: '1G',
      wait_ready: true,
      listen_timeout: 30000,
      kill_timeout: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: '/var/log/sealproof/admin-web-error.log',
      out_file: '/var/log/sealproof/admin-web-out.log',
    },
  ],
};
